### ISSUE TITLE
Replace WALA-callgraph submodule with our own fork

### ISSUE THREAD

**Issue by julbinb** [purpl-jb/dai-query#3]
- Fork https://github.com/bennostein/WALA-callgraph
- Apply the patch from `create-callgraph` branch of dai-query
- Check if the code from the latest commit [6c47f4](https://github.com/bennostein/WALA-callgraph/commit/6c47f4c2346d83df9da379709f797bd26cf61ebd) still produces a callgraph that works for `usertest/usertest.ml` from `create-callgraph` branch of dai-query. If not, roll back to [5c1d4](https://github.com/bennostein/WALA-callgraph/commit/5c1d47a0860f62ea5978a0123f9d383432fe2eea)
- Commit
- Replace WALA-callgraph submodule of dai-query with the fork

**Comment by kartva** [comment]
It appears that I don't have the permissions to fork the repository with @purpl-jb as the owner. Would you be fine with it having @DesmondWillowbrook as the owner?

**Comment by julbinb** [comment]
Ah, let me fork it and add you.

**Comment by julbinb** [comment]
https://github.com/purpl-jb/WALA-callgraph

**Comment by julbinb** [comment]
@DesmondWillowbrook Once this done, could you merge the callgraph branch to master?

**Comment by kartva** [comment]
So the way I ran `usertest.ml` is:
```
make && DAI_ROOT="../" dune runtest usertest
```
in the root of the repository. Is there a better command for running the tests?

**Comment by julbinb** [comment]
> So the way I ran `usertest.ml` is:
> 
> ```
> make && DAI_ROOT="../" dune runtest usertest
> ```
> 
> in the root of the repository. Is there a better command for running the tests?

Not really. I am using `./run_usertest.sh`, which additionally creates `.ps` files for generated `.dot` files.
