### ISSUE TITLE
build-callgraph.py is missing .jar-file generation

### ISSUE THREAD

**Issue by julbinb** [purpl-jb/dai-query#6]
https://github.com/purpl-jb/dai-query/blob/d74fc77fd6a4ab5250110575268cd405213358a0/build-callgraph.py#L21-L34

WALA-callgraph requires a jar file as an input, but `build-callgraph.py` only produces `.class` files. 
Thus, when I am trying to use the script for a new .java file, it fails with:

```
Exception in thread "main" java.nio.file.NoSuchFileException: /home/julia/Work/abs-int/dai-query/usertest/SimpleFuns.jar
```

See [readme](https://github.com/purpl-jb/WALA-callgraph/tree/master) for jar-file generation.

**Comment by kartva** [comment]
Should be fixed by latest commit.

**Comment by julbinb** [comment]
Perfect, thanks!
